<?xml version="1.0"?>
<package format="2">

  <name>pairs_uav_path_loader</name>
  <version>1.0.0</version>
  <description>The Path Loader package</description>

  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>

  <license>BSD 3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cmake_modules</depend>
  <depend>nodelet</depend>
  <depend>roscpp</depend>
  <depend>pairs_lib</depend>
  <depend>pairs_msgs</depend>

  <export>
    <nodelet plugin="${prefix}/nodelets.xml" />
  </export>

</package>
